version: 2

builds:
  - main: .
    binary: nepenthe
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ryanwersal/nepenthe/cmd.version={{.Version}}
      - -X github.com/ryanwersal/nepenthe/cmd.commit={{.ShortCommit}}
      - -X github.com/ryanwersal/nepenthe/cmd.date={{.Date}}

archives:
  - format: tar.gz
    files:
      - LICENSE

brews:
  - repository:
      owner: ryanwersal
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: nepenthe
    homepage: https://github.com/ryanwersal/nepenthe
    description: Selective forgetfulness for macOS Time Machine
    license: GPL-3.0
    custom_block: |
      depends_on :macos
    install: |
      bin.install "nepenthe"
    test: |
      system bin/"nepenthe", "version"
    service: |
      run [opt_bin/"nepenthe", "scan", "--accept-consents", "--log-format", "json"]
      run_type :interval
      interval 86400
      log_path var/"log/nepenthe/stdout.log"
      error_log_path var/"log/nepenthe/stderr.log"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
